-- CampusO: AYBU İşletme Fakültesi gerçek ders programı verisi
-- Kaynak: kullanıcının paylaştığı AYBÜ İşletme Fakültesi 2025-2026 güz/bahar
-- ders programı görselleri (İşletme, Finans ve Bankacılık, Uluslararası Ticaret
-- ve İşletmecilik, Yönetim Bilişim Sistemleri bölümleri). Ortak 1-2. sınıf
-- çekirdek dersleri (BUS1xx/2xx, ENG1xx/2xx, TDL1xx, TİT1xx) dört bölüme de
-- eklenmiştir; bölüme özgü dersler yalnız ilgili bölüme eklenmiştir.
-- Not: gerçek görsellerde yer almayan (bu dönem programında görünmeyen)
-- seçmeli dersler bilinçli olarak eklenmedi — uydurma veri girilmedi.
-- Not 2: baslangic_saat/bitis_saat BİLEREK girilmedi — ders saatleri dönemden
-- döneme (2026-27 güz/bahar vb.) değişebildiği için sabit saat yazılmadı.
-- Bu yüzden önce bu iki alan zorunlu olmaktan çıkarılıyor, sonra veri ekleniyor;
-- kesin saat belli olunca admin panelinden ayrıca girilebilir.

begin;

alter table public.ders_programi
  alter column baslangic_saat drop not null,
  alter column bitis_saat drop not null;

delete from public.ders_programi
where bolum in ('İşletme', 'Finans ve Bankacılık', 'Uluslararası Ticaret ve İşletmecilik', 'Yönetim Bilişim Sistemleri');

insert into public.ders_programi (bolum, sinif, ders_kodu, ders_adi, gun, derslik, hoca_adi) values
('İşletme', '1', 'MIS104', 'Introduction to Information Systems', 'Pazartesi', 'B202', 'Doç.Dr. Vildan Ateş'),
('Finans ve Bankacılık', '1', 'MIS104', 'Introduction to Information Systems', 'Pazartesi', 'B202', 'Doç.Dr. Vildan Ateş'),
('Uluslararası Ticaret ve İşletmecilik', '2', 'BUS210', 'Introduction to Marketing', 'Pazartesi', 'B201', 'Dr. Öğr. Üyesi Mustafa Ünsalan'),
('Yönetim Bilişim Sistemleri', '2', 'BUS210', 'Introduction to Marketing', 'Pazartesi', 'B201', 'Dr. Öğr. Üyesi Mustafa Ünsalan'),
('Finans ve Bankacılık', '2', 'BF204', 'Introduction to Banking', 'Pazartesi', 'B237', 'Prof.Dr. Yüksel Akay Ünvan'),
('Yönetim Bilişim Sistemleri', '3', 'MIS372', 'Forecasting', 'Pazartesi', 'B210', 'Doç.Dr. Keziban Seçkin Çodal'),
('Uluslararası Ticaret ve İşletmecilik', '3', 'ITB344', 'International Business II', 'Pazartesi', 'B217', 'Doç.Dr. Hakan Dulkadiroğlu'),
('İşletme', '3', 'BUS306', 'Production and Services Management', 'Pazartesi', 'B211', 'Prof.Dr. Metehan Gündoğan'),
('Uluslararası Ticaret ve İşletmecilik', '4', 'ITB446', 'Turkish Economy', 'Pazartesi', 'B212', 'Doç.Dr. Seda Ekmen Özçelik'),
('İşletme', '4', 'BUS428', 'Special Topics in Organizations', 'Pazartesi', 'B209', 'Dr. Öğr. Üyesi Sedat Ilgaz Günay'),
('Finans ve Bankacılık', '4', 'BF424', 'Monetary Policy and Central Banking', 'Pazartesi', 'B207', 'Doç. Dr. Cem Korkut'),
('Uluslararası Ticaret ve İşletmecilik', '1', 'MIS104', 'Introduction to Information Systems', 'Pazartesi', 'B202', 'Doç.Dr. Vildan Ateş'),
('Yönetim Bilişim Sistemleri', '1', 'MIS104', 'Introduction to Information Systems', 'Pazartesi', 'B202', 'Doç.Dr. Vildan Ateş'),
('İşletme', '2', 'BUS210', 'Introduction to Marketing', 'Pazartesi', 'B201', 'Dr. Öğr. Üyesi Mustafa Ünsalan'),
('Finans ve Bankacılık', '2', 'BUS210', 'Introduction to Marketing', 'Pazartesi', 'B201', 'Dr. Öğr. Üyesi Mustafa Ünsalan'),
('Uluslararası Ticaret ve İşletmecilik', '3', 'ITB306', 'Export Import Management', 'Pazartesi', 'B211', 'Doç.Dr. Seda Ekmen Özçelik'),
('Yönetim Bilişim Sistemleri', '3', 'MIS310', 'Probability', 'Pazartesi', 'B212', 'Doç.Dr. Keziban Seçkin Çodal'),
('İşletme', '3', 'BUS322', 'Comparative Business Systems', 'Pazartesi', 'B209', 'Dr. Öğr. Üyesi Sedat Ilgaz Günay'),
('Yönetim Bilişim Sistemleri', '4', 'MIS446', 'E-Government and Public Transformation', 'Pazartesi', 'B220', 'Prof.Dr. Ömür Akdemir'),
('İşletme', '4', 'BUS410', 'Organization Theory', 'Pazartesi', 'B237', 'Prof.Dr. Kerim Özcan'),
('Uluslararası Ticaret ve İşletmecilik', '4', 'ITB426', 'Human Resource Information Systems', 'Pazartesi', 'B207', 'Doç.Dr. Hakan Dulkadiroğlu'),
('Finans ve Bankacılık', '4', 'BF422', 'Export Financing and Eximbank Applications', 'Pazartesi', 'B217', 'Prof.Dr. Yüksel Akay Ünvan'),
('Finans ve Bankacılık', '2', 'TİT102', 'Türk İnkılap Tarihi II', 'Pazartesi', 'Online', 'Dr. Öğr. Üyesi Betül Tezcan'),
('Uluslararası Ticaret ve İşletmecilik', '2', 'TİT102', 'Türk İnkılap Tarihi II', 'Pazartesi', 'Online', 'Dr. Öğr. Üyesi Betül Tezcan'),
('Yönetim Bilişim Sistemleri', '2', 'TİT102', 'Türk İnkılap Tarihi II', 'Pazartesi', 'Online', 'Dr. Öğr. Üyesi Betül Tezcan'),
('İşletme', '1', 'ITB102', 'Introduction to Economics II', 'Salı', 'B201', 'Doç.Dr. Merve Karacaer'),
('Uluslararası Ticaret ve İşletmecilik', '1', 'ITB102', 'Introduction to Economics II', 'Salı', 'B201', 'Doç.Dr. Merve Karacaer'),
('Finans ve Bankacılık', '2', 'BF202', 'Financial Management', 'Salı', 'B237', 'Prof.Dr. Ayhan Kapusuzoğlu'),
('Yönetim Bilişim Sistemleri', '2', 'BF202', 'Financial Management', 'Salı', 'B237', 'Prof.Dr. Ayhan Kapusuzoğlu'),
('İşletme', '2', 'BUS204', 'Organizational Behaviour', 'Salı', 'B202', 'Doç.Dr. Hande Özgen'),
('Uluslararası Ticaret ve İşletmecilik', '2', 'BUS204', 'Organizational Behaviour', 'Salı', 'B202', 'Doç.Dr. Hande Özgen'),
('Finans ve Bankacılık', '3', 'BF304', 'Financial Markets and Institutions', 'Salı', 'B217', 'Prof.Dr. Nildağ Başak Ceylan'),
('İşletme', '3', 'BUS326', 'Research Methods', 'Salı', 'B211', 'Dr. Öğr. Üyesi İsmail Çağrı Doğan'),
('Yönetim Bilişim Sistemleri', '4', 'MIS406', 'Introduction to Social Network Analysis', 'Salı', 'B220', 'Prof.Dr. Derya Fındık'),
('Uluslararası Ticaret ve İşletmecilik', '4', 'ITB440', 'Qualitative Research', 'Salı', 'B210', 'Dr. Öğr. Üyesi Melek Mutioğlu Özkesen'),
('Finans ve Bankacılık', '1', 'ITB102', 'Introduction to Economics II', 'Salı', 'B201', 'Doç.Dr. Merve Karacaer'),
('Yönetim Bilişim Sistemleri', '1', 'ITB102', 'Introduction to Economics II', 'Salı', 'B201', 'Doç.Dr. Merve Karacaer'),
('Yönetim Bilişim Sistemleri', '2', 'MIS204', 'Database Management', 'Salı', 'B212', 'Doç.Dr. Vildan Ateş'),
('Finans ve Bankacılık', '2', 'BUS204', 'Organizational Behaviour', 'Salı', 'B202', 'Doç.Dr. Hande Özgen'),
('Finans ve Bankacılık', '3', 'BF308', 'Investment', 'Salı', 'B237', 'Prof.Dr. Ayhan Kapusuzoğlu'),
('Yönetim Bilişim Sistemleri', '3', 'MIS362', 'Innovation and Technology Management', 'Salı', 'B211', 'Prof.Dr. Derya Fındık'),
('İşletme', '4', 'BUS442', 'Enterprise Resource Planning', 'Salı', 'RZ LAB', 'Prof.Dr. Rafet Aktaş'),
('Finans ve Bankacılık', '4', 'BF402', 'Bank Management', 'Salı', 'B217', 'Prof.Dr. Nildağ Başak Ceylan'),
('Yönetim Bilişim Sistemleri', '4', 'MIS405', 'Fuzzy Systems', 'Salı', 'B209', 'Dr. Öğr. Üyesi Mazlum Özçağdavul'),
('İşletme', '1', 'BUS110', 'Social Psychology', 'Çarşamba', 'B202', 'Dr. Öğr. Üyesi İpek Mete Tönge'),
('Yönetim Bilişim Sistemleri', '1', 'BUS110', 'Social Psychology', 'Çarşamba', 'B202', 'Dr. Öğr. Üyesi İpek Mete Tönge'),
('Finans ve Bankacılık', '1', 'ENG102', 'Academic English II', 'Çarşamba', 'Online', 'Öğr.Gör. Ümit Tekir'),
('Uluslararası Ticaret ve İşletmecilik', '1', 'ENG102', 'Academic English II', 'Çarşamba', 'Online', 'Öğr.Gör. Ümit Tekir'),
('İşletme', '2', 'BUS202', 'Statistics for Business II', 'Çarşamba', 'B237', 'Dr. Öğr. Üyesi Ali İhsan Çetin'),
('Uluslararası Ticaret ve İşletmecilik', '2', 'BUS202', 'Statistics for Business II', 'Çarşamba', 'B237', 'Dr. Öğr. Üyesi Ali İhsan Çetin'),
('Yönetim Bilişim Sistemleri', '2', 'MIS210', 'Computer Networks and Security', 'Çarşamba', 'RZ LAB', 'Dr. Öğr. Üyesi Mazlum Özçağdavul'),
('İşletme', '3', 'BUS334', 'Digital Marketing', 'Çarşamba', 'B210', 'Dr. Öğr. Üyesi Mustafa Ünsalan'),
('Finans ve Bankacılık', '3', 'BF310', 'Multivariate Statistical Analysis', 'Çarşamba', 'B207', 'Doç.Dr. İklim Gedik Balay'),
('Uluslararası Ticaret ve İşletmecilik', '3', 'ITB389', 'Global Economic Actors and Trade Policy', 'Çarşamba', 'B212', 'Dr. Öğr. Üyesi Melek Mutioğlu Özkesen'),
('İşletme', '4', 'BUS414', 'Decision Making Techniques', 'Çarşamba', 'B209', 'Dr. Öğr. Üyesi Safa Arslan'),
('Yönetim Bilişim Sistemleri', '4', 'MIS410', 'Information Law', 'Çarşamba', 'B220', 'Dr. Öğr. Üyesi Musab Talha Akpınar'),
('Finans ve Bankacılık', '1', 'BUS110', 'Social Psychology', 'Çarşamba', 'B202', 'Dr. Öğr. Üyesi İpek Mete Tönge'),
('Uluslararası Ticaret ve İşletmecilik', '1', 'BUS110', 'Social Psychology', 'Çarşamba', 'B202', 'Dr. Öğr. Üyesi İpek Mete Tönge'),
('Yönetim Bilişim Sistemleri', '3', 'MIS301', 'Web Programming', 'Çarşamba', 'RZ LAB', 'Dr. Öğr. Üyesi Mazlum Özçağdavul'),
('İşletme', '4', 'BUS412', 'Impact Evaluation Method', 'Çarşamba', 'B210', 'Dr. Öğr. Üyesi Safa Arslan'),
('Finans ve Bankacılık', '4', 'BF417', 'Portfolio Management', 'Çarşamba', 'B237', 'Dr. Öğr. Üyesi Ali İhsan Çetin'),
('Yönetim Bilişim Sistemleri', '4', 'MIS441', 'Enterprise Information Systems', 'Çarşamba', 'B212', 'Dr. Öğr. Üyesi Musab Talha Akpınar'),
('Uluslararası Ticaret ve İşletmecilik', '4', 'ITB486', 'Nations, Politics and Markets', 'Çarşamba', 'B217', 'Dr. Öğr. Üyesi Melek Mutioğlu Özkesen'),
('İşletme', '1', 'BUS112', 'Introduction to Sociology', 'Perşembe', 'B202', 'Dr. Öğr. Üyesi Murat Ulubay'),
('Finans ve Bankacılık', '1', 'BUS112', 'Introduction to Sociology', 'Perşembe', 'B202', 'Dr. Öğr. Üyesi Murat Ulubay'),
('Uluslararası Ticaret ve İşletmecilik', '1', 'BUS104', 'Calculus for Business II', 'Perşembe', 'B201', 'Dr. Öğr. Üyesi Ali İhsan Çetin'),
('Yönetim Bilişim Sistemleri', '1', 'BUS104', 'Calculus for Business II', 'Perşembe', 'B201', 'Dr. Öğr. Üyesi Ali İhsan Çetin'),
('İşletme', '2', 'BF202', 'Financial Management', 'Perşembe', 'B237', 'Doç.Dr. Bilge Canbaloğlu'),
('Uluslararası Ticaret ve İşletmecilik', '2', 'BF202', 'Financial Management', 'Perşembe', 'B237', 'Doç.Dr. Bilge Canbaloğlu'),
('Finans ve Bankacılık', '2', 'BUS202', 'Statistics for Business II', 'Perşembe', 'B217', 'Doç.Dr. İklim Gedik Balay'),
('Yönetim Bilişim Sistemleri', '2', 'BUS202', 'Statistics for Business II', 'Perşembe', 'B217', 'Doç.Dr. İklim Gedik Balay'),
('Uluslararası Ticaret ve İşletmecilik', '3', 'ITB302', 'International Trade and Business Law', 'Perşembe', 'B211', 'Dr. Öğr. Üyesi Zehra Aycı'),
('Yönetim Bilişim Sistemleri', '3', 'MIS303', 'Digital Systems', 'Perşembe', 'B220', 'Prof.Dr. Hüseyin Demirel'),
('İşletme', '3', 'BUS308', 'Cost Accounting', 'Perşembe', 'B212', 'Doç.Dr. Kürşad Çavuşoğlu'),
('İşletme', '4', 'BUS438', 'Performance and Compensation Management', 'Perşembe', 'B210', 'Dr. Öğr. Üyesi İpek Mete Tönge'),
('Uluslararası Ticaret ve İşletmecilik', '4', 'ITB410', 'Corporate Sustainability Practices: Global Frameworks and Reporting Standards', 'Perşembe', 'B209', 'Doç.Dr. Merve Karacaer'),
('Uluslararası Ticaret ve İşletmecilik', '1', 'BUS112', 'Introduction to Sociology', 'Perşembe', 'B202', 'Dr. Öğr. Üyesi Murat Ulubay'),
('İşletme', '1', 'BUS104', 'Calculus for Business II', 'Perşembe', 'B201', 'Dr. Öğr. Üyesi Ali İhsan Çetin'),
('Finans ve Bankacılık', '1', 'BUS104', 'Calculus for Business II', 'Perşembe', 'B201', 'Dr. Öğr. Üyesi Ali İhsan Çetin'),
('Yönetim Bilişim Sistemleri', '3', 'MIS394', 'Internet of Things', 'Perşembe', 'B212', 'Prof.Dr. Hüseyin Demirel'),
('Uluslararası Ticaret ve İşletmecilik', '3', 'ITB312', 'International Economics II', 'Perşembe', 'B211', 'Doç.Dr. Bilge Canbaloğlu'),
('Finans ve Bankacılık', '3', 'BF302', 'Econometrics II', 'Perşembe', 'B237', 'Doç.Dr. İklim Gedik Balay'),
('İşletme', '3', 'BUS318', 'Sustainability and Business', 'Perşembe', 'B209', 'Doç.Dr. Semih Ceyhan'),
('İşletme', '4', 'BUS420', 'Artificial Intelligence and Business Strategy', 'Perşembe', 'B210', 'Doç.Dr. Haroon Muzaffar'),
('İşletme', '1', 'TDL102', 'Türk Dili II', 'Perşembe', 'Online', 'Dr. Öğr. Üyesi Ceren Selvi'),
('Finans ve Bankacılık', '1', 'TDL102', 'Türk Dili II', 'Perşembe', 'Online', 'Dr. Öğr. Üyesi Ceren Selvi'),
('Uluslararası Ticaret ve İşletmecilik', '1', 'TDL102', 'Türk Dili II', 'Perşembe', 'Online', 'Dr. Öğr. Üyesi Ceren Selvi'),
('Yönetim Bilişim Sistemleri', '1', 'TDL102', 'Türk Dili II', 'Perşembe', 'Online', 'Dr. Öğr. Üyesi Ceren Selvi'),
('İşletme', '2', 'ENG202', 'Academic English IV', 'Cuma', 'Online', 'Öğr.Gör. Yasemin Özbudak Ketik'),
('Yönetim Bilişim Sistemleri', '2', 'ENG202', 'Academic English IV', 'Cuma', 'Online', 'Öğr.Gör. Yasemin Özbudak Ketik'),
('Uluslararası Ticaret ve İşletmecilik', '1', 'BUS106', 'Accounting II', 'Cuma', 'B201', 'Doç.Dr. Kürşad Çavuşoğlu'),
('Finans ve Bankacılık', '1', 'BUS106', 'Accounting II', 'Cuma', 'B201', 'Doç.Dr. Kürşad Çavuşoğlu'),
('Finans ve Bankacılık', '2', 'ENG202', 'Academic English IV', 'Cuma', 'Online', 'Öğr.Gör. Ümit Tekir'),
('Uluslararası Ticaret ve İşletmecilik', '2', 'ENG202', 'Academic English IV', 'Cuma', 'Online', 'Öğr.Gör. Ümit Tekir'),
('İşletme', '2', 'BUS200', 'Human Resource Management', 'Cuma', 'B217', 'Prof.Dr. Hasan Engin Şener'),
('İşletme', '3', 'BUS324', 'Cross-Cultural Management', 'Cuma', 'B212', 'Öğr.Gör.Dr. İlay Hicret Öztürk Kayalak'),
('Finans ve Bankacılık', '3', 'BF306', 'Financial Data Analytics', 'Cuma', 'B237', 'Dr. Öğr. Üyesi Ali İhsan Çetin'),
('İşletme', '4', 'BUS418', 'Machine Learning for Business', 'Cuma', 'RZ LAB', 'Prof.Dr. Rafet Aktaş'),
('Uluslararası Ticaret ve İşletmecilik', '4', 'ITB448', 'International Service Trade', 'Cuma', 'B210', 'Doç.Dr. Ali Aycı'),
('İşletme', '1', 'BUS106', 'Accounting II', 'Cuma', 'B201', 'Doç.Dr. Kürşad Çavuşoğlu'),
('Yönetim Bilişim Sistemleri', '1', 'BUS106', 'Accounting II', 'Cuma', 'B201', 'Doç.Dr. Kürşad Çavuşoğlu'),
('İşletme', '2', 'ENG202', 'Academic English IV', 'Cuma', 'Online', 'Öğr.Gör. Yasemin Özbudak Ketik'),
('Yönetim Bilişim Sistemleri', '2', 'ENG202', 'Academic English IV', 'Cuma', 'Online', 'Öğr.Gör. Yasemin Özbudak Ketik'),
('Uluslararası Ticaret ve İşletmecilik', '3', 'ITB342', 'International Negotiations and Sales Management', 'Cuma', 'B237', 'Doç.Dr. Ali Aycı'),
('Finans ve Bankacılık', '4', 'BF404', 'Financial Modelling', 'Cuma', 'B210', 'Dr. Öğr. Üyesi Ali İhsan Çetin'),
('İşletme', '4', 'BUS444', 'Strategic Brand Management', 'Cuma', 'B211', 'Prof.Dr. Özge Gökbulut Özdemir'),
('İşletme', '2', 'TİT102', 'Türk İnkılap Tarihi II', 'Cuma', 'Online', 'Dr. Öğr. Üyesi Betül Tezcan'),
('İşletme', '1', 'BUS105', 'Accounting I', 'Pazartesi', 'B201', 'Doç.Dr. Kürşad Çavuşoğlu'),
('Finans ve Bankacılık', '1', 'BUS105', 'Accounting I', 'Pazartesi', 'B201', 'Doç.Dr. Kürşad Çavuşoğlu'),
('Uluslararası Ticaret ve İşletmecilik', '1', 'BUS105', 'Accounting I', 'Pazartesi', 'B201', 'Doç.Dr. Kürşad Çavuşoğlu'),
('Yönetim Bilişim Sistemleri', '1', 'BUS105', 'Accounting I', 'Pazartesi', 'B201', 'Doç.Dr. Kürşad Çavuşoğlu'),
('İşletme', '1', 'BUS103', 'Calculus for Business I', 'Salı', 'B201', 'Dr. Öğr. Üyesi Semih Ceyhan'),
('Finans ve Bankacılık', '1', 'BUS103', 'Calculus for Business I', 'Salı', 'B201', 'Dr. Öğr. Üyesi Semih Ceyhan'),
('Uluslararası Ticaret ve İşletmecilik', '1', 'BUS103', 'Calculus for Business I', 'Salı', 'B201', 'Dr. Öğr. Üyesi Semih Ceyhan'),
('Yönetim Bilişim Sistemleri', '1', 'BUS103', 'Calculus for Business I', 'Salı', 'B201', 'Dr. Öğr. Üyesi Semih Ceyhan'),
('İşletme', '1', 'ITB101', 'Introduction to Economics I', 'Çarşamba', 'B201', 'Doç.Dr. Merve Karacaer'),
('Finans ve Bankacılık', '1', 'ITB101', 'Introduction to Economics I', 'Çarşamba', 'B201', 'Doç.Dr. Merve Karacaer'),
('Uluslararası Ticaret ve İşletmecilik', '1', 'ITB101', 'Introduction to Economics I', 'Çarşamba', 'B201', 'Doç.Dr. Merve Karacaer'),
('Yönetim Bilişim Sistemleri', '1', 'ITB101', 'Introduction to Economics I', 'Çarşamba', 'B201', 'Doç.Dr. Merve Karacaer'),
('Yönetim Bilişim Sistemleri', '1', 'MIS105', 'Introduction to Algorithms and Programming', 'Perşembe', 'B210', 'Dr. Öğr. Üyesi Hakan Demirel'),
('İşletme', '1', 'BUS107', 'Introduction to Business', 'Perşembe', 'B201', 'Dr. Öğr. Üyesi Semih Ceyhan'),
('Finans ve Bankacılık', '1', 'BUS107', 'Introduction to Business', 'Perşembe', 'B201', 'Dr. Öğr. Üyesi Semih Ceyhan'),
('Uluslararası Ticaret ve İşletmecilik', '1', 'BUS107', 'Introduction to Business', 'Perşembe', 'B201', 'Dr. Öğr. Üyesi Semih Ceyhan'),
('Yönetim Bilişim Sistemleri', '1', 'BUS107', 'Introduction to Business', 'Perşembe', 'B201', 'Dr. Öğr. Üyesi Semih Ceyhan'),
('İşletme', '1', 'ENG101', 'Academic English I', 'Cuma', 'Online', 'Dr. Öğr. Üyesi Kadir Baysal'),
('Finans ve Bankacılık', '1', 'ENG101', 'Academic English I', 'Cuma', 'Online', 'Dr. Öğr. Üyesi Kadir Baysal'),
('Uluslararası Ticaret ve İşletmecilik', '1', 'ENG101', 'Academic English I', 'Cuma', 'Online', 'Dr. Öğr. Üyesi Kadir Baysal'),
('Yönetim Bilişim Sistemleri', '1', 'ENG101', 'Academic English I', 'Cuma', 'Online', 'Dr. Öğr. Üyesi Kadir Baysal'),
('İşletme', '1', 'TDL101', 'Türk Dili I', 'Pazartesi', 'Online', 'Dr. Öğr. Üyesi Ceren Selvi'),
('Finans ve Bankacılık', '1', 'TDL101', 'Türk Dili I', 'Pazartesi', 'Online', 'Dr. Öğr. Üyesi Ceren Selvi'),
('Uluslararası Ticaret ve İşletmecilik', '1', 'TDL101', 'Türk Dili I', 'Pazartesi', 'Online', 'Dr. Öğr. Üyesi Ceren Selvi'),
('Yönetim Bilişim Sistemleri', '1', 'TDL101', 'Türk Dili I', 'Pazartesi', 'Online', 'Dr. Öğr. Üyesi Ceren Selvi'),
('İşletme', '1', 'TİT101', 'Türk İnkılap Tarihi I', 'Cuma', 'Online', 'Dr. Öğr. Üyesi Betül Tezcan'),
('Finans ve Bankacılık', '1', 'TİT101', 'Türk İnkılap Tarihi I', 'Cuma', 'Online', 'Dr. Öğr. Üyesi Betül Tezcan'),
('Uluslararası Ticaret ve İşletmecilik', '1', 'TİT101', 'Türk İnkılap Tarihi I', 'Cuma', 'Online', 'Dr. Öğr. Üyesi Betül Tezcan'),
('Yönetim Bilişim Sistemleri', '1', 'TİT101', 'Türk İnkılap Tarihi I', 'Cuma', 'Online', 'Dr. Öğr. Üyesi Betül Tezcan'),
('İşletme', '2', 'BUS211', 'History of Science and Technology', 'Pazartesi', 'B202', 'Dr. Öğr. Üyesi Murat Ulubay'),
('Finans ve Bankacılık', '2', 'BUS211', 'History of Science and Technology', 'Pazartesi', 'B202', 'Dr. Öğr. Üyesi Murat Ulubay'),
('Uluslararası Ticaret ve İşletmecilik', '2', 'BUS211', 'History of Science and Technology', 'Pazartesi', 'B202', 'Dr. Öğr. Üyesi Murat Ulubay'),
('Yönetim Bilişim Sistemleri', '2', 'BUS211', 'History of Science and Technology', 'Pazartesi', 'B202', 'Dr. Öğr. Üyesi Murat Ulubay'),
('Yönetim Bilişim Sistemleri', '2', 'MIS215', 'Computer Programming II', 'Salı', 'B207', 'İbrahim Tolga Medeni'),
('Yönetim Bilişim Sistemleri', '2', 'MIS213', 'E-Business', 'Çarşamba', 'B202', 'Dr. Öğr. Üyesi Musab Talha Akpınar'),
('İşletme', '2', 'BUS201', 'Statistics for Business I', 'Perşembe', 'B202', 'Doç.Dr. İklim Gedik Balay'),
('Finans ve Bankacılık', '2', 'BUS201', 'Statistics for Business I', 'Perşembe', 'B202', 'Doç.Dr. İklim Gedik Balay'),
('Uluslararası Ticaret ve İşletmecilik', '2', 'BUS201', 'Statistics for Business I', 'Perşembe', 'B202', 'Doç.Dr. İklim Gedik Balay'),
('Yönetim Bilişim Sistemleri', '2', 'BUS201', 'Statistics for Business I', 'Perşembe', 'B202', 'Doç.Dr. İklim Gedik Balay'),
('Yönetim Bilişim Sistemleri', '2', 'MIS217', 'Fundamentals of Information Technologies', 'Perşembe', 'B210', 'Dr. Öğr. Üyesi Hakan Demirel'),
('İşletme', '2', 'ENG201', 'Academic English III', 'Cuma', 'Online', 'Dr. Öğr. Üyesi Kadir Baysal'),
('Finans ve Bankacılık', '2', 'ENG201', 'Academic English III', 'Cuma', 'Online', 'Dr. Öğr. Üyesi Kadir Baysal'),
('Uluslararası Ticaret ve İşletmecilik', '2', 'ENG201', 'Academic English III', 'Cuma', 'Online', 'Dr. Öğr. Üyesi Kadir Baysal'),
('Yönetim Bilişim Sistemleri', '2', 'ENG201', 'Academic English III', 'Cuma', 'Online', 'Dr. Öğr. Üyesi Kadir Baysal'),
('Yönetim Bilişim Sistemleri', '3', 'MIS303', 'Software Development', 'Pazartesi', 'B237', 'Prof.Dr. Ömür Akdemir'),
('Yönetim Bilişim Sistemleri', '3', 'MIS353', 'Management of IS Projects', 'Pazartesi', 'B212', 'Tuncay Doğu Medeni'),
('Yönetim Bilişim Sistemleri', '3', 'MIS321', 'Operations Management', 'Salı', 'B212', 'Doç.Dr. Vildan Ateş'),
('Yönetim Bilişim Sistemleri', '3', 'MIS307', 'Information System Analysis and Design', 'Salı', 'B220', 'Doç.Dr. Vildan Ateş'),
('Yönetim Bilişim Sistemleri', '3', 'MIS305', 'Operating Systems', 'Çarşamba', 'B211', 'İbrahim Tolga Medeni'),
('Yönetim Bilişim Sistemleri', '4', 'MIS488', 'Digital Forensics', 'Salı', 'B209', 'Dr. Öğr. Üyesi Mazlum Özçağdavul'),
('Yönetim Bilişim Sistemleri', '4', 'MIS403', 'Introduction to Artificial Intelligence', 'Çarşamba', 'B211', 'İbrahim Tolga Medeni'),
('Yönetim Bilişim Sistemleri', '4', 'MIS475', 'Smart Cities and Systems', 'Çarşamba', 'B209', 'Dr. Öğr. Üyesi Mazlum Özçağdavul'),
('Yönetim Bilişim Sistemleri', '4', 'MIS453', 'Social Media', 'Perşembe', 'B211', 'Doç.Dr. Keziban Seçkin Çodal'),
('Yönetim Bilişim Sistemleri', '4', 'MIS402', 'Business Intelligence and Data Mining', 'Perşembe', 'B211', 'Doç.Dr. Keziban Seçkin Çodal'),
('Yönetim Bilişim Sistemleri', '4', 'MIS425', 'Technology and Society', 'Cuma', 'B211', 'Prof.Dr. Derya Fındık'),
('Yönetim Bilişim Sistemleri', '4', 'MIS406', 'Introduction to Social Network Analysis', 'Cuma', 'B237 BZLAB', 'Prof.Dr. Derya Fındık');

commit;
